gpu_list:
  - 0
  - 1
  - 2
  - 3
seed: 37
dump_path: './outputs/'
model:
  num_output_channels: 2
defaults:
  - data: SK5_rock
  - data/dataset: SK_cnn
  - model: resnet152
  - engine: regression
  - tasks/train: train_resnet
  - optimizers@tasks.train.optimizers: adam
  - loss@tasks.train.loss: angular
  - sampler@tasks.train.data_loaders.train.sampler: subset_random
  - sampler@tasks.train.data_loaders.validation.sampler: subset_random
  - tasks/restore_best_state: restore_best_state
  - tasks/evaluate: test
  - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
  - _self_
